#!/usr/bin/env python3
"""One-time asset extraction from the base ROM.

Writes editable asset files under assets/ plus assets/manifest.json, which the
disassembly emitter uses to replace the corresponding ROM ranges with
`.incbin "build/assets/<name>.bin"` (regenerated by tools/assets/build.py).

  graphics  raw 4bpp tiles  -> assets/gfx/*.png (indexed, palette as displayed in game)
            LCW compressed  -> assets/gfx/*.png + original stream (kept if unmodified)
  palettes  128-byte CRAM images -> assets/palettes/*.pal (text, Mega Drive colour words)
  sound     Z80 driver, GEMS patch / envelope / sequence banks -> assets/sound/*.bin
            GEMS sample banks -> header + one .wav per sample segment
"""
import sys, os, json, struct, pickle, wave
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE); sys.path.insert(0, os.path.join(ROOT, 'tools', 'disasm'))
import lcw
from gfx import write_png, DEFAULT_PAL

DATA_START = 0x1FA82          # everything below is code (plus small data islands)


def main():
    rom = open(os.path.join(ROOT, 'baserom.gen'), 'rb').read()
    A, labels = pickle.load(open(os.path.join(ROOT, 'build', 'analysis.pkl'), 'rb'))
    probe = json.load(open(os.path.join(ROOT, 'assets', 'probe.json')))
    outdir = os.path.join(ROOT, 'assets')
    for d in ('gfx', 'palettes', 'sound', 'sound/samples', 'sound/samples2'):
        os.makedirs(os.path.join(outdir, d), exist_ok=True)
    dptr_locs = set()
    for a, (k, t, b) in A.dptr.items():
        for i in range({'L': 4, 'A': 4, 'W': 2, 'R': 2, 'R8': 1}[k]):
            dptr_locs.add(a + i)

    def clean(s, e):
        return not any(x in dptr_locs for x in range(s, e)) and all(A.owner[x] < 0 for x in range(s, e))

    manifest = []
    taken = []

    def add(entry):
        for s, e in taken:
            if entry['start'] < e and s < entry['end']:
                return False
        taken.append((entry['start'], entry['end']))
        manifest.append(entry)
        return True

    # ---------------------------------------------------------------- sound
    snd = [
        ('z80_gems_driver', 0x8547E, 0x86CDF, 'Z80 sound driver (GEMS), copied to Z80 RAM at boot'),
        ('gems_patches', 0x86CE0, 0x880D5, 'GEMS instrument (patch) bank'),
        ('gems_envelopes', 0x880D5, 0x8820A, 'GEMS envelope bank'),
        ('gems_sequences', 0x8820A, 0x97E90, 'GEMS sequence bank (all music and sound effects)'),
        ('gems2_patches', 0x1B7614, 0x1B7871, 'GEMS instrument bank (rebuild: extra music set)'),
        ('gems2_envelopes', 0x1B7871, 0x1B7892, 'GEMS envelope bank (rebuild: extra music set)'),
        ('gems2_sequences', 0x1B7892, 0x1B817C, 'GEMS sequence bank (rebuild: extra music set)'),
    ]
    for name, s, e, desc in snd:
        fn = 'sound/%s.bin' % name
        open(os.path.join(outdir, fn), 'wb').write(rom[s:e])
        assert clean(s, e), name
        add({'name': name, 'start': s, 'end': e, 'kind': 'bin', 'file': fn, 'desc': desc})
    for name, base, end, sub in (('gems_samples', 0x97E90, 0x1B7614, 'samples'), ('gems2_samples', 0x1B817C, 0x1BF980, 'samples2')):
        entry = sample_bank(rom, base, end, outdir, sub, name)
        for seg in entry['segments']:
            assert clean(base + seg['offset'], base + seg['offset'] + seg['size']) or seg.get('asm'), (name, seg)
        add(entry)

    # ------------------------------------------------------------- palettes
    for src in probe['palettes']:
        name = 'pal_%06X' % src
        fn = 'palettes/%s.pal' % name
        words = struct.unpack('>64H', rom[src:src + 128])
        with open(os.path.join(outdir, fn), 'w') as f:
            f.write('; Mega Drive palette (CRAM image, 4 lines x 16 colours, 0000BBB0GGG0RRR0)\n')
            for line in range(4):
                f.write(' '.join('%04X' % w for w in words[line * 16:line * 16 + 16]) + '\n')
        if clean(src, src + 128):
            add({'name': name, 'start': src, 'end': src + 128, 'kind': 'palette', 'file': fn})

    # ------------------------------------------------------------- graphics
    width_of = {}
    for k, v in probe.get('gfx_width', {}).items():
        s_, l_ = (int(x, 16) for x in k.split(':'))
        width_of[s_] = v
    pal_of = {}
    for k, v in probe['gfx_palette'].items():
        s, l = (int(x, 16) for x in k.split(':'))
        pal_of[(s, l)] = v['colors']
    chunks = {}
    for src, ln, typ, dest in probe['dma']:
        if typ == 2 and ln % 32 == 0 and src >= DATA_START:
            chunks[(src, ln)] = pal_of.get((src, ln))
    for src, ln, dst in probe['copy']:
        if ln % 32 == 0 and src >= DATA_START:
            chunks.setdefault((src, ln), None)
    # merge overlapping / adjacent chunks with compatible palettes
    items = sorted(chunks.items())
    merged = []
    for (s, l), pal in items:
        e = s + l
        if merged and s <= merged[-1][1] and (pal is None or merged[-1][2] is None or pal == merged[-1][2]) \
                and (s - merged[-1][0]) % 32 == 0:
            m = merged[-1]
            m[1] = max(m[1], e); m[2] = m[2] or pal
        else:
            merged.append([s, e, pal])
    ngfx = 0
    for s, e, pal in merged:
        # split around pointers / code so that nothing relocatable ends up inside a blob
        cur = s
        while cur < e:
            end = cur
            while end < e and end not in dptr_locs and A.owner[end] < 0:
                end += 32
            end = min(end, e)
            if end - cur >= 32 and clean(cur, end):
                name = 'gfx_%06X' % cur
                fn = 'gfx/%s.png' % name
                colors = pal or DEFAULT_PAL
                tpr = width_of.get(cur, 16)
                write_png(os.path.join(outdir, fn), rom[cur:end], colors, tpr)
                if add({'name': name, 'start': cur, 'end': end, 'kind': 'tiles', 'file': fn,
                        'palette_known': pal is not None, 'width_tiles': tpr}):
                    ngfx += 1
            cur = max(end, cur + 32)
            while cur < e and (cur in dptr_locs or A.owner[cur] >= 0):
                cur += 2
    # LCW compressed graphics
    for src in (0x1810, 0x1C26):
        data, clen = lcw.decompress(rom, src)
        name = 'gfx_%06X_lcw' % src
        fn = 'gfx/%s.png' % name
        write_png(os.path.join(outdir, fn), data, DEFAULT_PAL)
        orig = 'gfx/%s.orig.lcw' % name
        open(os.path.join(outdir, orig), 'wb').write(rom[src:src + clen])
        if clean(src, src + clen):
            add({'name': name, 'start': src, 'end': src + clen, 'kind': 'lcw_tiles', 'file': fn, 'orig': orig,
                 'size': len(data)})

    manifest.sort(key=lambda m: m['start'])
    json.dump(manifest, open(os.path.join(outdir, 'manifest.json'), 'w'), indent=1)
    tot = sum(m['end'] - m['start'] for m in manifest)
    print('%d assets (%d graphics), %d bytes (%.1f%% of ROM)' % (len(manifest), ngfx, tot, 100.0 * tot / len(rom)))


def sample_bank(rom, base, end, outdir, sub, name):
    """Split a GEMS sample bank into its header table and one WAV per segment
    (a segment runs from one sample start to the next, so gaps are kept)."""
    hdr_len = None
    heads = []
    i = 0
    while hdr_len is None or base + i * 12 < base + hdr_len:
        fl, slsb, smsb, skip, ln, loop, endv = struct.unpack('<BHBHHHH', rom[base + i * 12:base + i * 12 + 12])
        st = (smsb << 16) | slsb
        heads.append({'flags': fl, 'start': st, 'length': ln})
        if ln and (hdr_len is None or st < hdr_len):
            hdr_len = st
        i += 1
    header = rom[base:base + hdr_len]
    hfn = 'sound/%s/header.bin' % sub
    open(os.path.join(outdir, hfn), 'wb').write(header)
    starts = sorted(set(h['start'] for h in heads if h['length'] and h['start'] >= hdr_len))
    starts.append(end - base)
    segs = []
    for a, b in zip(starts, starts[1:]):
        idx = [k for k, h in enumerate(heads) if h['start'] == a and h['length']]
        fn = 'sound/%s/seg_%06X_s%02X.wav' % (sub, a, idx[0]) if idx else 'sound/%s/seg_%06X.wav' % (sub, a)
        with wave.open(os.path.join(outdir, fn), 'wb') as w:
            w.setnchannels(1); w.setsampwidth(1); w.setframerate(10400)
            w.writeframes(rom[base + a:base + b])
        segs.append({'offset': a, 'size': b - a, 'file': fn, 'samples': idx})
    return {'name': name, 'start': base, 'end': end, 'kind': 'gems_samples', 'header': hfn,
            'count': len(heads), 'segments': segs,
            'desc': 'GEMS DAC sample bank: 12-byte headers (flags, start24, skip, len, loop, end; little endian) + 8-bit PCM'}


if __name__ == '__main__':
    main()
